### ISSUE TITLE
Where is the mistake?

### ISSUE THREAD

**Issue by UnixCro** [amitupreti/Instagram-Follower-Scraper#5]
python -V Python 2.7.16
python3 -V  Python 3.8.2
macOS Catalina 10.15.7 
```
root@macOS Instagram-Follower-Scraper # python instabot.py 
Traceback (most recent call last):
  File "instabot.py", line 6, in <module>
    import pathlib
ImportError: No module named pathlib
```

```
root@macOS Instagram-Follower-Scraper # python3 instabot.py 
Traceback (most recent call last):
  File "instabot.py", line 20, in <module>
    L.login('username', 'password')        # (login)
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 483, in login
    self.context.login(user, passwd)
  File "/Library/Python/3.8/site-packages/instaloader/instaloadercontext.py", line 254, in login
    raise BadCredentialsException('Login error: Wrong password.')
instaloader.exceptions.BadCredentialsException: Login error: Wrong password.

```

**Comment by kafarik** [comment]
I have the same error

**Comment by Miap93** [comment]
I have the same issue. any solution?

**Comment by Miap93** [comment]
problem solved: open instabot in notepad and introduce your instagram account name and password in ln20  in the corresponding fields
